import type { AppEnvironment } from '../app/models';

/**
 * Auto-generated by scripts/build-for-vm.mjs — do not edit by hand.
 * Regenerate with: CSI_NORA_PUBLIC_ORIGIN="http://42.60.195.227:8090" npm run build:vm
 */
export const environment: AppEnvironment = {
  production: true,
  deploymentTier: 'production',
  allowUatOverride: false,
  appVersion: '4.2.0',
  backendBaseUrl: "http://42.60.195.227:8090",
  preferTokenBackend: true,
};
