/**
 * Generates src/environments/environment.vm.generated.ts from CSI_NORA_PUBLIC_ORIGIN.
 * Run before: ng build --configuration=vm
 *
 * Example (PowerShell):
 *   $env:CSI_NORA_PUBLIC_ORIGIN="https://203.0.113.10"; npm run build:vm
 *
 * Example (bash):
 *   CSI_NORA_PUBLIC_ORIGIN=https://203.0.113.10 npm run build:vm
 *
 * Use https:// if TLS terminates on nginx; http:// only for lab HTTP.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

let raw = process.env.CSI_NORA_PUBLIC_ORIGIN?.trim();
if (!raw) {
  console.error(`
[build-for-vm] Missing environment variable CSI_NORA_PUBLIC_ORIGIN.

Set it to your public origin (scheme + host, optional port, no path), e.g.:
  https://203.0.113.10
  http://203.0.113.10:8080

Or pass a bare IP/host; https:// is assumed:
  203.0.113.10

Then run: npm run build:vm
`);
  process.exit(1);
}

if (!/^https?:\/\//i.test(raw)) {
  raw = `https://${raw}`;
}

let origin = raw.replace(/\/$/, '');
try {
  const u = new URL(origin);
  if (!u.hostname) {
    throw new Error('invalid URL');
  }
  origin = u.origin;
} catch {
  console.error('[build-for-vm] Invalid CSI_NORA_PUBLIC_ORIGIN:', process.env.CSI_NORA_PUBLIC_ORIGIN);
  process.exit(1);
}

const outPath = path.join(root, 'src', 'environments', 'environment.vm.generated.ts');
const ts = `import type { AppEnvironment } from '../app/models';

/**
 * Auto-generated by scripts/build-for-vm.mjs — do not edit by hand.
 * Regenerate with: CSI_NORA_PUBLIC_ORIGIN=${JSON.stringify(origin)} npm run build:vm
 */
export const environment: AppEnvironment = {
  production: true,
  deploymentTier: 'production',
  allowUatOverride: false,
  appVersion: '4.2.0',
  backendBaseUrl: ${JSON.stringify(origin)},
  preferTokenBackend: true,
};
`;

fs.writeFileSync(outPath, ts, 'utf8');
console.log('[build-for-vm] Wrote', outPath);
console.log('[build-for-vm] backendBaseUrl =', origin);
